### PR TITLE
Adjust to 2024-05-28 backend changes

### LINKED ISSUE #2: 2024-05-28 API updates and missing channels
Thanks for doing the work to reverse engineer and automate EPG fetching! I've been using your script for some time now but ran into a few hiccups after the TV7 updates on May 28, which also included many changes to the set of channels, channel names, and renumbering.

The first thing you may be interested to know is that the API appears to have a new (stable?) home at `https://api.tv.init7.net/api/`

The second thing I noticed is that some channels are missing in the API -- https://api.tv.init7.net/api/tvchannel/ includes data for 105 channels, but https://api.init7.net/tvchannels.m3u lists 212 (as of last night, anyway).

The missing channel IDs are:
> 24Horas.es 5Plus.ch 5STAR.uk 5USA.uk 6Plus.ch ARDalpha.de AlJazeera.qa AnixeHDSerie.de AuftankenTV.ch BBCFour.uk BBCNewsEurope.uk BNTV.ba BVN.nl BibelTV.de CBBC.uk CBeebies.uk CNNTurk.tr CanalPlus.fr Cartoonito.it Channel5.uk Cine34.it ComedyCentral.de DMAX.de DMAX.it DWEnglish.de DeejayTV.it DeluxeMusic.de DreamTurk.tr Duna.hu EuroD.tr EuroStar.tr FashionTVEurope.fr Film4.uk Focus.it France24English.fr France24French.fr France5.fr Frisbee.it Giallo.it Haberturk.tr ITV3.uk ITV4.uk K2.it Kanal7.tr LFMTV.ch LiloTV.de MDRFernsehenSachsen.de MTV.de More4.uk N24Doku.de NDRFernsehenHamburg.de Nitro.de Nove.it One.de OneTV.ch ProSiebenMaxx.de RMCStory.fr RTK1.xk RTL1025TV.it RTPInternacional.pt RTSH3.al RTSSvet.rs RadioItaliaTV.it Rai5.it RaiScuola.it RaiStoria.it RealTime.it RougeTV.ch SAT1Gold.de SRFernsehen.de ServusTV.at SkyNewsInternational.uk Sportitalia.it StarTV.ch SuperTennis.it TELE5.de TGRTEU.tr TLC.de TRT1.tr TRTCocuk.tr TRTHaber.tr TRTSpor.tr TRTTurk.tr TV2000.it TVCG.me TVEInternacionalEuropeAsia.es TVM3.ch TVPPolonia.pl TVRInternational.ro TVSuissePlus.ch TeleD.ch TeleSwizz.ch TeleVersoix.ch TeleZ.ch Telelombardia.it TravelXP.uk WELT.de WettercomTV.de ZDFinfo.de ZDFneo.de hrfernsehen.de kabeleinsDoku.de phoenix.de rbbFernsehenBerlin.de sixx.de tagesschau24.de tv4e.gr

(I guess the next step is seeing whether these channels are available with EPG in the app and/or doing some more reverse engineering -- just to be clear I don't expect you to do that but wanted to report my findings.)

### PR DESCRIPTION
**Pull request by chkuendig**
Fixes #2 - works for me but given the discussion in #2 I would appreciate feedback before I merge this.

### CODE REVIEW

**Comment by ne20002** [comment]
This fixes the problems even though it seems as if a few channels don't have an epg, e.g.
```
cat /tmp/tv7-epg-parser/getEPG-f96536ae-57f8-40e8-b9b4-2b05047ced3b.json
{"count":0,"next":null,"previous":null,"results":[]}
```
And 3+ and 4+ only have 15 minutes placeholders.

**Comment by chkuendig** [comment]
Good catch on the placeholders, I pushed an update to strip these (from what I can tell they are `Boing`, `Rai Sport+`,`TeleTicino`,`Télé Versoix`, `Canal Alpha NE`, `ShF`, `4+ HD`, and `3+ HD`).

Not much we can do currently on the few channels with empty EPGs.

**Comment by spali** [comment]
Just a side note ... if not already known... may be faster, but less "structured" execution.
So, as you anyway write everything in one huge xml which does not require to be sorted.
you can request all channel data at once (paged).

the following request actually delivers everything for all channels including the `channel` attribute with all data of the channel that come also with the channel list request.
``` 
'https://api.tv.init7.net/api/epg/?limit=20000&offset=0'
'https://api.tv.init7.net/api/epg/?limit=20000&offset=20000'
'https://api.tv.init7.net/api/epg/?limit=20000&offset=40000'
'https://api.tv.init7.net/api/epg/?limit=20000&offset=60000'
'https://api.tv.init7.net/api/epg/?limit=20000&offset=80000'
'https://api.tv.init7.net/api/epg/?limit=20000&offset=100000'
```
Hint: in my testing, it looks like a lot more than `20000` limit will return a server error.

depending on your OCD level, this would be more efficient, but harder to find wrong or missing data 😉

**Comment by 0xabu** [comment]
This seems to be working for me.

**Comment by chkuendig** [comment]
I added a quick check to keep track of channels with missing EPG, currently this seem to be 32 out of 212. Let's see whether this changes:

> Fetching EPG done. Total 212 channels, 32 channels missing EPG: 3+ HD, 4+ HD, auftanken.TV, BBC World News, Boing, Canal Alpha NE, CANAL+ en clair, Cine34, CNN Türk, Dream Türk, DW Europe, Euro D, Eurostar, Fashion TV, KANAL 7 AVRUPA, RadioItaliaTV, Rai Sport+, RTK 1, ShF, Tele D, Tele Z, Telelombardia, Teleswizz, TeleTicino, TGRT EU, TRT Cocuk, TRT Haber, TRT1, TV Suisse Plus, TVCG MNE, TVR International, Télé Versoix

@spali thanks, that would indeed be faster. But given we don't have any performance issues I prefer to keep this easier to debug.

**Pull request merged**
